obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.20
inflation_radius: 0.55
transform_tolerance: 1
observation_sources: scan
scan:
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true
