global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: true
  rolling_window: false
  width: 40.0
  height: 40.0
  resolution: 0.02
  origin_x: -20.0
  origin_y: -20.0
  plugins:
    - {name: static_layer,      type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}
