local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint #link

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.8  

  static_map: false  
  rolling_window: true
  width: 6
  height: 6
  resolution: 0.05
  
